# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bebeb29562ef2a4bb76861dad0d17ba171902f7a70e7238df0dfd9e7ccc7d129623281252ba597aed309b421dfb2d795acc1a5dd6d1d638db63e9bdcac474112

test:
  secret_key_base: 485861a3c80009a35621ee470fa0df804436202d7d69053ca7cd8fc9bb9acdd31a035619b91daabdf8fe9fa324c9099b6eb5bff802687821d93bf6ede13a6a6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
